### ISSUE TITLE
please help me patch qmi_wwan_simcom to work with arm64 kernel  raspberrypi 5.15.50-v8+

### ISSUE THREAD

**Issue by xevilstar** [geerlingguy/raspberry-pi-pcie-devices#455]
root@raspberrypi:/usr/src/qmi_wwan_simcom# make
rm -rf *.o *~ core .depend .*.cmd *.ko *.mod.c .cache.mk .tmp_versions Module.* modules.order
make -C /lib/modules/5.15.50-v8+/build M=/usr/src/qmi_wwan_simcom modules
make[1]: Entering directory '/usr/src/linux'
  CC [M]  /usr/src/qmi_wwan_simcom/qmi_wwan_simcom.o
/usr/src/qmi_wwan_simcom/qmi_wwan_simcom.c: In function ‘qmi_wwan_register_subdriver’:

/usr/src/qmi_wwan_simcom/qmi_wwan_simcom.c:227:13:` error: incompatible type for argument 4 of ‘usb_cdc_wdm_register’

  227 |       4096, &qmi_wwan_cdc_wdm_manage_power);

      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

      |             |

      |             int (*)(struct usb_interface *, int)

In file included from /usr/src/qmi_wwan_simcom/qmi_wwan_simcom.c:21:

./include/linux/usb/cdc-wdm.h:20:39: note: expected ‘enum wwan_port_type’ but argument is of type ‘int (*)(struct usb_interface *, int)’

   20 |      int bufsize, enum wwan_port_type type,

      |                   ~~~~~~~~~~~~~~~~~~~~^~~~

/usr/src/qmi_wwan_simcom/qmi_wwan_simcom.c:226:14: error: too few arguments to function ‘usb_cdc_wdm_register’

  226 |  subdriver = usb_cdc_wdm_register(info->control, &dev->status->desc,

      |              ^~~~~~~~~~~~~~~~~~~~

In file included from /usr/src/qmi_wwan_simcom/qmi_wwan_simcom.c:21:

./include/linux/usb/cdc-wdm.h:18:27: note: declared here

   18 | extern struct usb_driver *usb_cdc_wdm_register(struct usb_interface *intf,

      |                           ^~~~~~~~~~~~~~~~~~~~

make[2]: *** [scripts/Makefile.build:288: /usr/src/qmi_wwan_simcom/qmi_wwan_simcom.o] Error 1

make[1]: *** [Makefile:1871: /usr/src/qmi_wwan_simcom] Error 2

make[1]: Leaving directory '/usr/src/linux'

make: *** [Makefile:7: all] Error 2

root@raspberrypi:/usr/src/qmi_wwan_simcom# uname -a

Linux raspberrypi 5.15.50-v8+ #1 SMP PREEMPT Wed Jun 29 16:20:10 CEST 2022 aarch64 GNU/Linux

**Comment by 6by9** [comment]
Duplicated in https://github.com/raspberrypi/linux/issues/5072

**Comment by geerlingguy** [comment]
Thanks for posting this but this project is more for testing PCIe devices no the Pi, and this would be more of a support question for the Pi forums or elsewhere.
